CREATE TABLE user_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL UNIQUE,
    password_hash text,
    display_name text,
    status text NOT NULL DEFAULT 'active',
    role text NOT NULL DEFAULT 'user',
    oauth_provider text,
    oauth_id text,
    totp_secret text,
    totp_enabled boolean NOT NULL DEFAULT false,
    totp_backup_codes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    last_login_at timestamptz
);

CREATE UNIQUE INDEX ux_user_accounts_oauth
    ON user_accounts(oauth_provider, oauth_id)
    WHERE oauth_provider IS NOT NULL AND oauth_id IS NOT NULL;

CREATE TABLE user_api_keys (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email text NOT NULL,
    key_hash text NOT NULL UNIQUE,
    key_prefix text NOT NULL,
    name text,
    status text NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now(),
    last_used_at timestamptz
);

CREATE TABLE request_leases (
    lease_token text PRIMARY KEY,
    request_id text NOT NULL,
    api_key_hash text NOT NULL,
    api_key_id bigint NOT NULL,
    user_id bigint NOT NULL,
    account_id bigint NOT NULL,
    group_id bigint NOT NULL,
    model text NOT NULL,
    upstream_model text NOT NULL,
    inbound_endpoint text NOT NULL,
    rate_multiplier numeric(20, 8) NOT NULL,
    hold_handle text,
    hold_amount numeric(20, 8) NOT NULL,
    status text NOT NULL CHECK (status IN ('active', 'completed', 'aborted', 'expired')),
    final_cost_usd numeric(20, 8),
    abort_reason text,
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL,
    finalized_at timestamptz
);

CREATE INDEX ix_request_leases_request_id ON request_leases(request_id);
CREATE INDEX ix_request_leases_active_expiry ON request_leases(expires_at)
    WHERE status = 'active';

CREATE TABLE usage_events (
    lease_token text PRIMARY KEY REFERENCES request_leases(lease_token),
    request_id text NOT NULL,
    api_key_id bigint NOT NULL,
    user_id bigint NOT NULL,
    account_id bigint NOT NULL,
    group_id bigint NOT NULL,
    model text NOT NULL,
    upstream_model text NOT NULL,
    inbound_endpoint text NOT NULL,
    input_tokens integer NOT NULL,
    output_tokens integer NOT NULL,
    cache_create_tokens integer NOT NULL,
    cache_read_tokens integer NOT NULL,
    cost_usd numeric(20, 8) NOT NULL,
    duration_ms integer NOT NULL,
    first_token_ms integer NOT NULL,
    status_code integer NOT NULL,
    stream boolean NOT NULL,
    client_disconnect boolean NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX ux_usage_events_request_id ON usage_events(request_id);

CREATE TABLE usage_logs (
    request_id text PRIMARY KEY,
    lease_token text NOT NULL UNIQUE,
    api_key_id bigint NOT NULL,
    user_id bigint NOT NULL,
    account_id bigint NOT NULL,
    group_id bigint NOT NULL,
    model text NOT NULL,
    upstream_model text NOT NULL,
    input_tokens integer NOT NULL,
    output_tokens integer NOT NULL,
    cache_create_tokens integer NOT NULL,
    cache_read_tokens integer NOT NULL,
    cost_usd numeric(20, 8) NOT NULL,
    duration_ms integer NOT NULL,
    first_token_ms integer NOT NULL,
    stream boolean NOT NULL,
    client_disconnect boolean NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE usage_outbox (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lease_token text NOT NULL REFERENCES request_leases(lease_token),
    event_type text NOT NULL CHECK (event_type IN ('complete', 'abort', 'expire')),
    attempts integer NOT NULL DEFAULT 0,
    next_attempt_at timestamptz NOT NULL DEFAULT now(),
    processed_at timestamptz,
    last_error text,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (lease_token, event_type)
);

CREATE INDEX ix_usage_outbox_pending ON usage_outbox(next_attempt_at, id)
    WHERE processed_at IS NULL;
-- Greenfield business schema. All tables needed by the initial product are created
-- in this baseline; later migrations are forward-only product changes.
CREATE TABLE IF NOT EXISTS proxies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    type text NOT NULL DEFAULT 'http',
    host text NOT NULL,
    port integer NOT NULL DEFAULT 0,
    username text,
    password text,
    status text NOT NULL DEFAULT 'active',
    latency_ms integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL DEFAULT '',
    platform text NOT NULL DEFAULT 'anthropic',
    description text,
    rate_multiplier numeric(20,8) NOT NULL DEFAULT 1,
    is_exclusive boolean NOT NULL DEFAULT false,
    status text NOT NULL DEFAULT 'active',
    daily_limit_usd numeric(20,8),
    claude_code_only boolean NOT NULL DEFAULT false,
    fallback_group_id bigint,
    model_routing_enabled boolean NOT NULL DEFAULT false,
    model_routing jsonb NOT NULL DEFAULT '{}'::jsonb,
    member_account_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
    rpm_limit integer NOT NULL DEFAULT 0,
    peak_multiplier numeric(20,8),
    peak_start_hour integer,
    peak_end_hour integer,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_groups_name ON groups(name) WHERE name <> '';

CREATE TABLE IF NOT EXISTS accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    platform text NOT NULL,
    type text NOT NULL,
    base_url text NOT NULL DEFAULT '',
    credentials jsonb NOT NULL DEFAULT '{}'::jsonb,
    proxy_url text,
    tls_fingerprint boolean NOT NULL DEFAULT false,
    model_mapping jsonb NOT NULL DEFAULT '{}'::jsonb,
    supported_models jsonb NOT NULL DEFAULT '[]'::jsonb,
    concurrency integer NOT NULL DEFAULT 1,
    priority integer NOT NULL DEFAULT 50,
    load_factor integer NOT NULL DEFAULT 1,
    rate_multiplier numeric(20,8) NOT NULL DEFAULT 1,
    schedulable boolean NOT NULL DEFAULT true,
    status text NOT NULL DEFAULT 'active',
    error_message text,
    last_used_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);
CREATE INDEX IF NOT EXISTS ix_accounts_status ON accounts(status);
CREATE INDEX IF NOT EXISTS ix_accounts_platform ON accounts(platform);

CREATE TABLE IF NOT EXISTS account_groups (
    account_id bigint NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    group_id bigint NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    priority integer NOT NULL DEFAULT 50,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (account_id, group_id)
);

CREATE TABLE IF NOT EXISTS redeem_codes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL UNIQUE,
    type text NOT NULL DEFAULT 'balance',
    value numeric(20,8) NOT NULL DEFAULT 0,
    discount_amount numeric(20,2) NOT NULL DEFAULT 0,
    bonus_amount numeric(20,8) NOT NULL DEFAULT 0,
    max_uses integer NOT NULL DEFAULT 0,
    used_count integer NOT NULL DEFAULT 0,
    status text NOT NULL DEFAULT 'unused',
    used_by bigint,
    used_at timestamptz,
    expires_at timestamptz,
    last_redeemed_by bigint,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS payment_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key text,
    user_id bigint NOT NULL,
    amount numeric(20,2) NOT NULL DEFAULT 0,
    currency text NOT NULL DEFAULT 'USD',
    provider text NOT NULL DEFAULT '',
    provider_order_id text,
    status text NOT NULL DEFAULT 'pending',
    description text,
    created_at timestamptz NOT NULL DEFAULT now(),
    paid_at timestamptz
);

ALTER TABLE request_leases
    ADD CONSTRAINT ck_request_leases_amounts CHECK (hold_amount >= 0 AND (final_cost_usd IS NULL OR final_cost_usd >= 0));
CREATE UNIQUE INDEX IF NOT EXISTS ux_request_leases_request_id ON request_leases(request_id);

ALTER TABLE usage_outbox
    ADD COLUMN IF NOT EXISTS claimed_by text,
    ADD COLUMN IF NOT EXISTS claimed_until timestamptz,
    ADD COLUMN IF NOT EXISTS dead_lettered_at timestamptz;
CREATE INDEX IF NOT EXISTS ix_usage_outbox_claimable
    ON usage_outbox(next_attempt_at, id)
    WHERE processed_at IS NULL AND dead_lettered_at IS NULL;

CREATE TABLE IF NOT EXISTS settlement_effects (
    lease_token text NOT NULL,
    effect_type text NOT NULL,
    applied_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (lease_token, effect_type)
);

CREATE TABLE IF NOT EXISTS balance_holds (
    hold_id text PRIMARY KEY,
    user_id bigint NOT NULL,
    lease_token text,
    amount numeric(20, 8) NOT NULL CHECK (amount >= 0),
    status text NOT NULL CHECK (status IN ('active', 'released', 'committed')),
    created_at timestamptz NOT NULL DEFAULT now(),
    finalized_at timestamptz
);

CREATE TABLE IF NOT EXISTS balance_ledger (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    payment_id bigint,
    reference text,
    amount numeric(20, 8) NOT NULL CHECK (amount <> 0),
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_balance_ledger_payment
    ON balance_ledger(payment_id) WHERE payment_id IS NOT NULL;

ALTER TABLE payment_orders ADD COLUMN IF NOT EXISTS idempotency_key text;
CREATE UNIQUE INDEX IF NOT EXISTS ux_payment_orders_user_idempotency
    ON payment_orders(user_id, idempotency_key) WHERE idempotency_key IS NOT NULL;

ALTER TABLE user_api_keys ADD COLUMN IF NOT EXISTS api_key_id bigint NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS redeem_code_redemptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_id bigint NOT NULL REFERENCES redeem_codes(id),
    user_id bigint NOT NULL,
    bonus_amount numeric(20, 8) NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (code_id, user_id)
);
-- Complete the initial SQLSugar projection schema.
ALTER TABLE usage_logs
    ADD COLUMN IF NOT EXISTS upstream_model text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS first_token_ms integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS client_disconnect boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS announcements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL DEFAULT '',
    content text NOT NULL DEFAULT '',
    status text NOT NULL DEFAULT 'published',
    priority integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    action text NOT NULL DEFAULT '',
    resource_type text,
    resource_id text,
    details text,
    ip_address text,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_audit_logs_user_created ON audit_logs(user_id, created_at);

CREATE TABLE IF NOT EXISTS ops_metrics (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_name text NOT NULL,
    metric_value numeric(20,4) NOT NULL DEFAULT 0,
    labels text,
    collected_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_ops_metrics_name_collected ON ops_metrics(metric_name, collected_at);

CREATE TABLE IF NOT EXISTS subscription_plans (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL DEFAULT '',
    price_monthly numeric(20,2) NOT NULL DEFAULT 0,
    quota_usd numeric(20,2) NOT NULL DEFAULT 0,
    features text,
    status text NOT NULL DEFAULT 'active'
);

CREATE TABLE IF NOT EXISTS user_subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    plan_id bigint NOT NULL REFERENCES subscription_plans(id),
    status text NOT NULL DEFAULT 'active',
    started_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz
);
CREATE INDEX IF NOT EXISTS ix_user_subscriptions_user_status ON user_subscriptions(user_id, status);

CREATE TABLE IF NOT EXISTS channel_monitors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id bigint NOT NULL,
    status text NOT NULL DEFAULT 'unknown',
    latency_ms integer NOT NULL DEFAULT 0,
    last_error text,
    checked_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS usage_summary_daily (
    id text PRIMARY KEY,
    user_id bigint NOT NULL,
    model text NOT NULL DEFAULT '',
    date timestamptz NOT NULL,
    request_count integer NOT NULL DEFAULT 0,
    input_tokens bigint NOT NULL DEFAULT 0,
    output_tokens bigint NOT NULL DEFAULT 0,
    total_cost_usd numeric(20,6) NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS ix_usage_summary_daily_user_date ON usage_summary_daily(user_id, date);

CREATE TABLE IF NOT EXISTS referral_codes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    code text NOT NULL UNIQUE,
    total_referrals integer NOT NULL DEFAULT 0,
    total_bonus_usd numeric(20,2) NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS referral_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referrer_user_id bigint NOT NULL,
    referred_user_id bigint NOT NULL,
    bonus_usd numeric(20,2) NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (referrer_user_id, referred_user_id)
);

CREATE TABLE IF NOT EXISTS content_audit_rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern text NOT NULL DEFAULT '',
    action_type text NOT NULL DEFAULT 'log',
    scope text,
    status text NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS content_audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    request_id text,
    matched_rule text NOT NULL DEFAULT '',
    action text NOT NULL DEFAULT '',
    content_snippet text,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_content_audit_logs_user_created ON content_audit_logs(user_id, created_at);

CREATE TABLE IF NOT EXISTS tls_fingerprint_profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL DEFAULT '',
    ja3_hash text,
    ja4_hash text,
    cipher_suites text,
    status text NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now()
);

-- The target cache projection uses a separate durable row for API key metadata.
-- Key material is hashed; plaintext credentials are never persisted in projections.
ALTER TABLE user_api_keys
    ADD COLUMN IF NOT EXISTS api_key_id bigint NOT NULL DEFAULT 0;
-- Durable state for asynchronous image and video work.  Object bytes belong
-- in object storage; this table owns only metadata and provider task linkage.
CREATE TABLE IF NOT EXISTS media_operations (
    operation_id text PRIMARY KEY,
    idempotency_key text NOT NULL,
    operation_type text NOT NULL,
    status text NOT NULL CHECK (status IN ('pending', 'running', 'succeeded', 'failed', 'canceled', 'expired')),
    api_key_id bigint NOT NULL,
    account_id bigint NOT NULL,
    request_id text NOT NULL,
    lease_token text NOT NULL REFERENCES request_leases(lease_token),
    upstream_task_id text,
    progress integer NOT NULL DEFAULT 0 CHECK (progress BETWEEN 0 AND 100),
    output_metadata jsonb,
    error jsonb,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (api_key_id, idempotency_key)
);

CREATE INDEX IF NOT EXISTS ix_media_operations_active
    ON media_operations (status, expires_at, updated_at)
    WHERE status IN ('pending', 'running');
CREATE INDEX IF NOT EXISTS ix_media_operations_upstream_task
    ON media_operations (account_id, upstream_task_id)
    WHERE upstream_task_id IS NOT NULL;
ALTER TABLE usage_events
    ADD COLUMN IF NOT EXISTS input_image_count integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS output_image_count integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS image_size text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS video_count integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS video_resolution text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS video_duration_seconds integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS realtime_duration_ms integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS realtime_frames integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS disconnect_reason text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS provider_usage_json text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS reasoning_tokens integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS service_tier text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS upstream_endpoint text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS cancellation_reason text NOT NULL DEFAULT '';
ALTER TABLE usage_events
    ADD COLUMN IF NOT EXISTS media_operation_id text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS pricing_version text NOT NULL DEFAULT '';

ALTER TABLE usage_logs
    ADD COLUMN IF NOT EXISTS input_image_count integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS output_image_count integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS image_size text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS video_count integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS video_resolution text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS video_duration_seconds integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS realtime_duration_ms integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS realtime_frames integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS disconnect_reason text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS provider_usage_json text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS reasoning_tokens integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS service_tier text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS upstream_endpoint text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS cancellation_reason text NOT NULL DEFAULT '';
ALTER TABLE usage_logs
    ADD COLUMN IF NOT EXISTS media_operation_id text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS pricing_version text NOT NULL DEFAULT '';
ALTER TABLE media_operations
    ADD COLUMN IF NOT EXISTS request_fingerprint text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS provider text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS output_url text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS content_type text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS cancel_requested boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS attempts integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS next_poll_at timestamptz,
    ADD COLUMN IF NOT EXISTS last_polled_at timestamptz;

CREATE INDEX IF NOT EXISTS ix_media_operations_poll
    ON media_operations (next_poll_at, updated_at)
    WHERE status IN ('pending', 'running');
