CREATE TABLE user_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL UNIQUE,
    password_hash text,
    display_name text,
    status text NOT NULL DEFAULT 'active',
    role text NOT NULL DEFAULT 'user',
    oauth_provider text,
    oauth_id text,
    totp_secret text,
    totp_enabled boolean NOT NULL DEFAULT false,
    totp_backup_codes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    last_login_at timestamptz
);

CREATE UNIQUE INDEX ux_user_accounts_oauth
    ON user_accounts(oauth_provider, oauth_id)
    WHERE oauth_provider IS NOT NULL AND oauth_id IS NOT NULL;

CREATE TABLE user_api_keys (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email text NOT NULL,
    key_hash text NOT NULL UNIQUE,
    key_prefix text NOT NULL,
    name text,
    status text NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now(),
    last_used_at timestamptz
);

CREATE TABLE request_leases (
    lease_token text PRIMARY KEY,
    request_id text NOT NULL,
    api_key_hash text NOT NULL,
    api_key_id bigint NOT NULL,
    user_id bigint NOT NULL,
    account_id bigint NOT NULL,
    group_id bigint NOT NULL,
    model text NOT NULL,
    upstream_model text NOT NULL,
    inbound_endpoint text NOT NULL,
    rate_multiplier numeric(20, 8) NOT NULL,
    hold_handle text,
    hold_amount numeric(20, 8) NOT NULL,
    status text NOT NULL CHECK (status IN ('active', 'completed', 'aborted', 'expired')),
    final_cost_usd numeric(20, 8),
    abort_reason text,
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL,
    finalized_at timestamptz
);

CREATE INDEX ix_request_leases_request_id ON request_leases(request_id);
CREATE INDEX ix_request_leases_active_expiry ON request_leases(expires_at)
    WHERE status = 'active';

CREATE TABLE usage_events (
    lease_token text PRIMARY KEY REFERENCES request_leases(lease_token),
    request_id text NOT NULL,
    api_key_id bigint NOT NULL,
    user_id bigint NOT NULL,
    account_id bigint NOT NULL,
    group_id bigint NOT NULL,
    model text NOT NULL,
    upstream_model text NOT NULL,
    inbound_endpoint text NOT NULL,
    input_tokens integer NOT NULL,
    output_tokens integer NOT NULL,
    cache_create_tokens integer NOT NULL,
    cache_read_tokens integer NOT NULL,
    cost_usd numeric(20, 8) NOT NULL,
    duration_ms integer NOT NULL,
    first_token_ms integer NOT NULL,
    status_code integer NOT NULL,
    stream boolean NOT NULL,
    client_disconnect boolean NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX ux_usage_events_request_id ON usage_events(request_id);

CREATE TABLE usage_logs (
    request_id text PRIMARY KEY,
    lease_token text NOT NULL UNIQUE,
    api_key_id bigint NOT NULL,
    user_id bigint NOT NULL,
    account_id bigint NOT NULL,
    group_id bigint NOT NULL,
    model text NOT NULL,
    upstream_model text NOT NULL,
    input_tokens integer NOT NULL,
    output_tokens integer NOT NULL,
    cache_create_tokens integer NOT NULL,
    cache_read_tokens integer NOT NULL,
    cost_usd numeric(20, 8) NOT NULL,
    duration_ms integer NOT NULL,
    first_token_ms integer NOT NULL,
    stream boolean NOT NULL,
    client_disconnect boolean NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE usage_outbox (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lease_token text NOT NULL REFERENCES request_leases(lease_token),
    event_type text NOT NULL CHECK (event_type IN ('complete', 'abort', 'expire')),
    attempts integer NOT NULL DEFAULT 0,
    next_attempt_at timestamptz NOT NULL DEFAULT now(),
    processed_at timestamptz,
    last_error text,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (lease_token, event_type)
);

CREATE INDEX ix_usage_outbox_pending ON usage_outbox(next_attempt_at, id)
    WHERE processed_at IS NULL;
