-- Additive safety migration for lease idempotency, outbox ownership and billing.
-- The first target migration intentionally only created the request/usage tables.
-- These base tables must exist before this migration adds their safety constraints.
CREATE TABLE IF NOT EXISTS proxies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    type text NOT NULL DEFAULT 'http',
    host text NOT NULL,
    port integer NOT NULL DEFAULT 0,
    username text,
    password text,
    status text NOT NULL DEFAULT 'active',
    latency_ms integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL DEFAULT '',
    platform text NOT NULL DEFAULT 'anthropic',
    description text,
    rate_multiplier numeric(20,8) NOT NULL DEFAULT 1,
    is_exclusive boolean NOT NULL DEFAULT false,
    status text NOT NULL DEFAULT 'active',
    daily_limit_usd numeric(20,8),
    claude_code_only boolean NOT NULL DEFAULT false,
    fallback_group_id bigint,
    model_routing_enabled boolean NOT NULL DEFAULT false,
    model_routing jsonb NOT NULL DEFAULT '{}'::jsonb,
    member_account_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
    rpm_limit integer NOT NULL DEFAULT 0,
    peak_multiplier numeric(20,8),
    peak_start_hour integer,
    peak_end_hour integer,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_groups_name ON groups(name) WHERE name <> '';

CREATE TABLE IF NOT EXISTS accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    platform text NOT NULL,
    type text NOT NULL,
    base_url text NOT NULL DEFAULT '',
    credentials jsonb NOT NULL DEFAULT '{}'::jsonb,
    proxy_url text,
    tls_fingerprint boolean NOT NULL DEFAULT false,
    model_mapping jsonb NOT NULL DEFAULT '{}'::jsonb,
    supported_models jsonb NOT NULL DEFAULT '[]'::jsonb,
    concurrency integer NOT NULL DEFAULT 1,
    priority integer NOT NULL DEFAULT 50,
    load_factor integer NOT NULL DEFAULT 1,
    rate_multiplier numeric(20,8) NOT NULL DEFAULT 1,
    schedulable boolean NOT NULL DEFAULT true,
    status text NOT NULL DEFAULT 'active',
    error_message text,
    last_used_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);
CREATE INDEX IF NOT EXISTS ix_accounts_status ON accounts(status);
CREATE INDEX IF NOT EXISTS ix_accounts_platform ON accounts(platform);

CREATE TABLE IF NOT EXISTS account_groups (
    account_id bigint NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    group_id bigint NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    priority integer NOT NULL DEFAULT 50,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (account_id, group_id)
);

CREATE TABLE IF NOT EXISTS redeem_codes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL UNIQUE,
    type text NOT NULL DEFAULT 'balance',
    value numeric(20,8) NOT NULL DEFAULT 0,
    status text NOT NULL DEFAULT 'unused',
    used_by bigint,
    used_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS payment_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key text,
    user_id bigint NOT NULL,
    amount numeric(20,2) NOT NULL DEFAULT 0,
    currency text NOT NULL DEFAULT 'USD',
    provider text NOT NULL DEFAULT '',
    provider_order_id text,
    status text NOT NULL DEFAULT 'pending',
    description text,
    created_at timestamptz NOT NULL DEFAULT now(),
    paid_at timestamptz
);

ALTER TABLE request_leases
    ADD CONSTRAINT ck_request_leases_amounts CHECK (hold_amount >= 0 AND (final_cost_usd IS NULL OR final_cost_usd >= 0));
CREATE UNIQUE INDEX IF NOT EXISTS ux_request_leases_request_id ON request_leases(request_id);

ALTER TABLE usage_outbox
    ADD COLUMN IF NOT EXISTS claimed_by text,
    ADD COLUMN IF NOT EXISTS claimed_until timestamptz,
    ADD COLUMN IF NOT EXISTS dead_lettered_at timestamptz;
CREATE INDEX IF NOT EXISTS ix_usage_outbox_claimable
    ON usage_outbox(next_attempt_at, id)
    WHERE processed_at IS NULL AND dead_lettered_at IS NULL;

CREATE TABLE IF NOT EXISTS settlement_effects (
    lease_token text NOT NULL,
    effect_type text NOT NULL,
    applied_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (lease_token, effect_type)
);

CREATE TABLE IF NOT EXISTS balance_holds (
    hold_id text PRIMARY KEY,
    user_id bigint NOT NULL,
    lease_token text,
    amount numeric(20, 8) NOT NULL CHECK (amount >= 0),
    status text NOT NULL CHECK (status IN ('active', 'released', 'committed')),
    created_at timestamptz NOT NULL DEFAULT now(),
    finalized_at timestamptz
);

CREATE TABLE IF NOT EXISTS balance_ledger (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    payment_id bigint,
    reference text,
    amount numeric(20, 8) NOT NULL CHECK (amount <> 0),
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_balance_ledger_payment
    ON balance_ledger(payment_id) WHERE payment_id IS NOT NULL;

ALTER TABLE payment_orders ADD COLUMN IF NOT EXISTS idempotency_key text;
CREATE UNIQUE INDEX IF NOT EXISTS ux_payment_orders_user_idempotency
    ON payment_orders(user_id, idempotency_key) WHERE idempotency_key IS NOT NULL;

ALTER TABLE user_api_keys ADD COLUMN IF NOT EXISTS api_key_id bigint NOT NULL DEFAULT 0;
ALTER TABLE redeem_codes ADD COLUMN IF NOT EXISTS last_redeemed_by bigint;
CREATE TABLE IF NOT EXISTS redeem_code_redemptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_id bigint NOT NULL REFERENCES redeem_codes(id),
    user_id bigint NOT NULL,
    bonus_amount numeric(20, 8) NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (code_id, user_id)
);
