-- Product-native forward migration for versioned pricing and reconciliation.
CREATE TABLE pricing_versions (
    version text PRIMARY KEY,
    model text NOT NULL,
    input_usd_per_million numeric(20,8) NOT NULL CHECK (input_usd_per_million >= 0),
    output_usd_per_million numeric(20,8) NOT NULL CHECK (output_usd_per_million >= 0),
    cache_read_usd_per_million numeric(20,8) NOT NULL DEFAULT 0 CHECK (cache_read_usd_per_million >= 0),
    cache_write_usd_per_million numeric(20,8) NOT NULL DEFAULT 0 CHECK (cache_write_usd_per_million >= 0),
    effective_from timestamptz NOT NULL,
    effective_until timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (effective_until IS NULL OR effective_until > effective_from)
);
CREATE INDEX ix_pricing_versions_model_effective
    ON pricing_versions(model, effective_from DESC);

CREATE TABLE ledger_reconciliation_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    status text NOT NULL CHECK (status IN ('running', 'passed', 'failed')),
    ledger_total numeric(20,8) NOT NULL DEFAULT 0,
    hold_total numeric(20,8) NOT NULL DEFAULT 0,
    mismatch_total numeric(20,8) NOT NULL DEFAULT 0,
    details jsonb NOT NULL DEFAULT '{}'::jsonb
);
