-- G0 target schema completion and migration control plane.
-- This migration is additive and is intentionally independent of Orleans' serialized
-- grain state. CDC applies semantic events through grains and uses these tables only
-- for durable inbox/checkpoint/fence bookkeeping.

-- Keep the SQLSugar projection schema complete even when the application starts
-- against a database created from the original 000/001 migrations.
ALTER TABLE usage_logs
    ADD COLUMN IF NOT EXISTS upstream_model text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS first_token_ms integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS client_disconnect boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS announcements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL DEFAULT '',
    content text NOT NULL DEFAULT '',
    status text NOT NULL DEFAULT 'published',
    priority integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    action text NOT NULL DEFAULT '',
    resource_type text,
    resource_id text,
    details text,
    ip_address text,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_audit_logs_user_created ON audit_logs(user_id, created_at);

CREATE TABLE IF NOT EXISTS ops_metrics (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_name text NOT NULL,
    metric_value numeric(20,4) NOT NULL DEFAULT 0,
    labels text,
    collected_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_ops_metrics_name_collected ON ops_metrics(metric_name, collected_at);

CREATE TABLE IF NOT EXISTS subscription_plans (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL DEFAULT '',
    price_monthly numeric(20,2) NOT NULL DEFAULT 0,
    quota_usd numeric(20,2) NOT NULL DEFAULT 0,
    features text,
    status text NOT NULL DEFAULT 'active'
);

CREATE TABLE IF NOT EXISTS user_subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    plan_id bigint NOT NULL REFERENCES subscription_plans(id),
    status text NOT NULL DEFAULT 'active',
    started_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz
);
CREATE INDEX IF NOT EXISTS ix_user_subscriptions_user_status ON user_subscriptions(user_id, status);

CREATE TABLE IF NOT EXISTS channel_monitors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id bigint NOT NULL,
    status text NOT NULL DEFAULT 'unknown',
    latency_ms integer NOT NULL DEFAULT 0,
    last_error text,
    checked_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS usage_summary_daily (
    id text PRIMARY KEY,
    user_id bigint NOT NULL,
    model text NOT NULL DEFAULT '',
    date timestamptz NOT NULL,
    request_count integer NOT NULL DEFAULT 0,
    input_tokens bigint NOT NULL DEFAULT 0,
    output_tokens bigint NOT NULL DEFAULT 0,
    total_cost_usd numeric(20,6) NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS ix_usage_summary_daily_user_date ON usage_summary_daily(user_id, date);

CREATE TABLE IF NOT EXISTS referral_codes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    code text NOT NULL UNIQUE,
    total_referrals integer NOT NULL DEFAULT 0,
    total_bonus_usd numeric(20,2) NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS referral_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referrer_user_id bigint NOT NULL,
    referred_user_id bigint NOT NULL,
    bonus_usd numeric(20,2) NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (referrer_user_id, referred_user_id)
);

CREATE TABLE IF NOT EXISTS content_audit_rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern text NOT NULL DEFAULT '',
    action_type text NOT NULL DEFAULT 'log',
    scope text,
    status text NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS content_audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    request_id text,
    matched_rule text NOT NULL DEFAULT '',
    action text NOT NULL DEFAULT '',
    content_snippet text,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_content_audit_logs_user_created ON content_audit_logs(user_id, created_at);

CREATE TABLE IF NOT EXISTS tls_fingerprint_profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL DEFAULT '',
    ja3_hash text,
    ja4_hash text,
    cipher_suites text,
    status text NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now()
);

-- The target cache projection uses a separate durable row for API key metadata.
-- The key material itself remains hashed; plaintext credentials never enter CDC.
ALTER TABLE user_api_keys
    ADD COLUMN IF NOT EXISTS api_key_id bigint NOT NULL DEFAULT 0;

-- Durable migration fencing. Exactly one row is authoritative at any epoch.
CREATE TABLE IF NOT EXISTS migration_fence (
    id smallint PRIMARY KEY CHECK (id = 1),
    epoch bigint NOT NULL CHECK (epoch > 0),
    write_primary text NOT NULL CHECK (write_primary IN ('sub2api', 'platform')),
    mode text NOT NULL CHECK (mode IN ('legacy_primary', 'target_canary', 'target_primary', 'legacy_read_only')),
    reason text NOT NULL DEFAULT '',
    updated_by text NOT NULL DEFAULT 'bootstrap',
    updated_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO migration_fence(id, epoch, write_primary, mode)
VALUES (1, 1, 'sub2api', 'legacy_primary')
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS cdc_inbox (
    event_id text PRIMARY KEY,
    epoch bigint NOT NULL,
    source_lsn text NOT NULL,
    transaction_id text NOT NULL,
    aggregate_type text NOT NULL,
    aggregate_id text NOT NULL,
    operation text NOT NULL CHECK (operation IN ('insert', 'update', 'delete', 'snapshot')),
    schema_version integer NOT NULL,
    payload_hash text NOT NULL,
    envelope jsonb NOT NULL,
    status text NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'processing', 'applied', 'failed', 'dead_letter')),
    attempts integer NOT NULL DEFAULT 0,
    last_error text,
    received_at timestamptz NOT NULL DEFAULT now(),
    applied_at timestamptz,
    next_attempt_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_cdc_inbox_pending ON cdc_inbox(next_attempt_at, received_at)
    WHERE status IN ('pending', 'failed');
CREATE INDEX IF NOT EXISTS ix_cdc_inbox_aggregate ON cdc_inbox(aggregate_type, aggregate_id, source_lsn);

CREATE TABLE IF NOT EXISTS cdc_checkpoints (
    connector_name text PRIMARY KEY,
    source_lsn text,
    snapshot_completed boolean NOT NULL DEFAULT false,
    last_event_id text,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS cdc_dead_letters (
    event_id text PRIMARY KEY REFERENCES cdc_inbox(event_id) ON DELETE CASCADE,
    envelope jsonb NOT NULL,
    reason text NOT NULL,
    attempts integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    replayed_at timestamptz
);

CREATE TABLE IF NOT EXISTS cdc_sync_acks (
    event_id text PRIMARY KEY,
    epoch bigint NOT NULL,
    aggregate_type text NOT NULL,
    aggregate_id text NOT NULL,
    status text NOT NULL CHECK (status IN ('accepted', 'applied', 'rejected', 'failed')),
    error_code text,
    acked_at timestamptz NOT NULL DEFAULT now()
);

-- Restricted credential channel bookkeeping. The encrypted payload is supplied by
-- a separate ACL-protected topic and is never copied into ordinary cdc_inbox rows.
CREATE TABLE IF NOT EXISTS cdc_credential_payloads (
    event_id text PRIMARY KEY,
    epoch bigint NOT NULL,
    aggregate_type text NOT NULL,
    aggregate_id text NOT NULL,
    key_version text NOT NULL,
    ciphertext bytea NOT NULL,
    payload_hash text NOT NULL,
    applied_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS reconciliation_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epoch bigint NOT NULL,
    scope text NOT NULL,
    status text NOT NULL CHECK (status IN ('started', 'passed', 'failed')),
    source_count bigint NOT NULL DEFAULT 0,
    target_count bigint NOT NULL DEFAULT 0,
    mismatch_count bigint NOT NULL DEFAULT 0,
    started_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    details jsonb NOT NULL DEFAULT '{}'::jsonb
);
