-- Invalid broker records cannot enter cdc_inbox, but they must remain auditable.
-- Store only their digest and location so a rejected secret is never copied into
-- another plaintext persistence surface.
CREATE TABLE IF NOT EXISTS cdc_rejected_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connector_name text NOT NULL,
    topic text NOT NULL,
    partition_id integer NOT NULL,
    offset_value bigint NOT NULL,
    message_sha256 text NOT NULL,
    message_bytes integer NOT NULL,
    reason text NOT NULL,
    received_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (topic, partition_id, offset_value)
);

CREATE INDEX IF NOT EXISTS ix_cdc_rejected_messages_received
    ON cdc_rejected_messages(received_at DESC);
