-- Immutable control-plane history for promotion, rollback and audit windows.
CREATE TABLE IF NOT EXISTS migration_fence_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_epoch bigint NOT NULL,
    to_epoch bigint NOT NULL UNIQUE,
    from_primary text NOT NULL,
    from_mode text NOT NULL,
    to_primary text NOT NULL,
    to_mode text NOT NULL,
    reason text NOT NULL,
    updated_by text NOT NULL,
    transitioned_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_migration_fence_events_time
    ON migration_fence_events (transitioned_at DESC, id DESC);
