-- Provider webhook delivery is an append-only idempotency boundary. A pending
-- event may be retried after a process crash until its balance effect is applied.
CREATE TABLE payment_webhook_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider text NOT NULL,
    event_id text NOT NULL,
    event_type text NOT NULL,
    payment_id bigint,
    payload_hash text NOT NULL,
    status text NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'applied', 'rejected')),
    error text,
    received_at timestamptz NOT NULL DEFAULT now(),
    applied_at timestamptz,
    UNIQUE (provider, event_id)
);

CREATE INDEX ix_payment_webhook_events_payment
    ON payment_webhook_events(payment_id, received_at DESC);
