ALTER TABLE user_subscriptions
    ADD COLUMN IF NOT EXISTS idempotency_key text,
    ADD COLUMN IF NOT EXISTS provider text NOT NULL DEFAULT 'internal',
    ADD COLUMN IF NOT EXISTS external_reference text,
    ADD COLUMN IF NOT EXISTS renewal_at timestamptz,
    ADD COLUMN IF NOT EXISTS cancelled_at timestamptz,
    ADD COLUMN IF NOT EXISTS quota_granted_usd numeric(20,8) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS quota_used_usd numeric(20,8) NOT NULL DEFAULT 0;

ALTER TABLE user_subscriptions
    DROP CONSTRAINT IF EXISTS ck_user_subscriptions_status;
ALTER TABLE user_subscriptions
    ADD CONSTRAINT ck_user_subscriptions_status
    CHECK (status IN ('active', 'cancelled', 'expired', 'past_due'));

CREATE UNIQUE INDEX IF NOT EXISTS ux_user_subscriptions_user_idempotency
    ON user_subscriptions(user_id, idempotency_key)
    WHERE idempotency_key IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_user_subscriptions_one_active
    ON user_subscriptions(user_id)
    WHERE status = 'active';
CREATE INDEX IF NOT EXISTS ix_user_subscriptions_expiry
    ON user_subscriptions(expires_at)
    WHERE status = 'active';

CREATE TABLE IF NOT EXISTS subscription_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id bigint NOT NULL REFERENCES user_subscriptions(id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES user_accounts(id) ON DELETE CASCADE,
    event_type text NOT NULL,
    idempotency_key text NOT NULL,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, event_type, idempotency_key)
);
CREATE INDEX IF NOT EXISTS ix_subscription_events_subscription
    ON subscription_events(subscription_id, created_at DESC);
