-- A timed-out request is not evidence that the Provider did no work. Keep its
-- reservation until durable usage arrives or an operator resolves the incident.
ALTER TABLE request_leases
    DROP CONSTRAINT IF EXISTS request_leases_status_check;
ALTER TABLE request_leases
    ADD CONSTRAINT request_leases_status_check
    CHECK (status IN ('active', 'completed', 'aborted', 'expired',
                      'reconciliation_needed'));
ALTER TABLE request_leases
    ADD COLUMN IF NOT EXISTS reconciliation_needed_at timestamptz;

ALTER TABLE request_idempotency
    DROP CONSTRAINT IF EXISTS request_idempotency_status_check;
ALTER TABLE request_idempotency
    ADD CONSTRAINT request_idempotency_status_check
    CHECK (status IN ('active', 'completed', 'aborted', 'expired',
                      'reconciliation_needed'));

ALTER TABLE usage_outbox
    DROP CONSTRAINT IF EXISTS usage_outbox_event_type_check;
ALTER TABLE usage_outbox
    ADD CONSTRAINT usage_outbox_event_type_check
    CHECK (event_type IN ('complete', 'abort', 'expire', 'reconcile'));

ALTER TABLE ledger_reconciliation_runs
    ADD COLUMN IF NOT EXISTS checked_accounts bigint NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS repaired_holds bigint NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS repaired_projections bigint NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS open_incidents bigint NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS resolved_incidents bigint NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS accounting_reconciliation_incidents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_key text NOT NULL UNIQUE CHECK (length(incident_key) BETWEEN 1 AND 500),
    kind text NOT NULL CHECK (length(kind) BETWEEN 1 AND 100),
    severity text NOT NULL CHECK (severity IN ('warning', 'critical')),
    user_id bigint,
    lease_token text,
    status text NOT NULL CHECK (status IN ('open', 'resolved')),
    expected jsonb NOT NULL DEFAULT '{}'::jsonb,
    actual jsonb NOT NULL DEFAULT '{}'::jsonb,
    occurrences bigint NOT NULL DEFAULT 1 CHECK (occurrences > 0),
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    resolved_at timestamptz,
    last_run_id bigint REFERENCES ledger_reconciliation_runs(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS ix_accounting_reconciliation_incidents_open
    ON accounting_reconciliation_incidents(severity, last_seen_at, id)
    WHERE status = 'open';
CREATE INDEX IF NOT EXISTS ix_accounting_reconciliation_incidents_user
    ON accounting_reconciliation_incidents(user_id, status, last_seen_at DESC)
    WHERE user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_accounting_reconciliation_incidents_lease
    ON accounting_reconciliation_incidents(lease_token, status, last_seen_at DESC)
    WHERE lease_token IS NOT NULL;
