-- Persist the point at which a Provider may have observed a request. A lease
-- that never left the Gateway can expire safely; any later stage must retain
-- its hold until usage or an explicit reconciliation decision arrives.
ALTER TABLE request_leases
    DROP CONSTRAINT IF EXISTS request_leases_status_check;

ALTER TABLE request_leases
    ADD COLUMN IF NOT EXISTS forwarded_at timestamptz,
    ADD COLUMN IF NOT EXISTS output_started_at timestamptz,
    ADD COLUMN IF NOT EXISTS provider_status_code integer
        CHECK (provider_status_code BETWEEN 100 AND 999);

-- Old `active` rows did not distinguish an unsent request from an in-flight
-- request. Preserve money by migrating them to the conservative state.
UPDATE request_leases
SET status = 'forwarded',
    forwarded_at = COALESCE(forwarded_at, created_at)
WHERE status = 'active';

ALTER TABLE request_leases
    ADD CONSTRAINT request_leases_status_check
    CHECK (status IN ('held', 'forwarded', 'output_started', 'completed',
                      'aborted', 'expired', 'reconciliation_needed'));

DROP INDEX IF EXISTS ix_request_leases_active_expiry;
CREATE INDEX ix_request_leases_open_expiry ON request_leases(expires_at, lease_token)
    WHERE status IN ('held', 'forwarded', 'output_started');

CREATE TABLE request_lease_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lease_token text NOT NULL REFERENCES request_leases(lease_token) ON DELETE CASCADE,
    event_type text NOT NULL CHECK (event_type IN (
        'held', 'forwarded', 'output_started', 'completed', 'aborted_no_charge',
        'aborted_unknown', 'expired', 'reconciliation_needed')),
    source text NOT NULL CHECK (length(source) BETWEEN 1 AND 100),
    detail text NOT NULL DEFAULT '' CHECK (length(detail) <= 500),
    provider_status_code integer CHECK (provider_status_code BETWEEN 100 AND 999),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (lease_token, event_type)
);

CREATE INDEX ix_request_lease_events_created
    ON request_lease_events(created_at, id);

INSERT INTO request_lease_events(lease_token, event_type, source, detail)
SELECT lease_token, status,
       'migration-020', 'state imported before dispatch evidence was available'
FROM request_leases
WHERE status IN ('forwarded', 'completed', 'expired', 'reconciliation_needed')
ON CONFLICT (lease_token, event_type) DO NOTHING;

INSERT INTO request_lease_events(lease_token, event_type, source, detail)
SELECT lease_token, 'aborted_no_charge',
       'migration-020', COALESCE(abort_reason, 'pre-evidence abort')
FROM request_leases
WHERE status = 'aborted'
ON CONFLICT (lease_token, event_type) DO NOTHING;
