-- An operator decision is a new product event, not an edit to historical data.
-- One incident can be resolved once; retries use the supplied idempotency key.
CREATE TABLE IF NOT EXISTS accounting_reconciliation_resolutions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id bigint NOT NULL UNIQUE
        REFERENCES accounting_reconciliation_incidents(id) ON DELETE RESTRICT,
    lease_token text NOT NULL
        REFERENCES request_leases(lease_token) ON DELETE RESTRICT,
    action text NOT NULL CHECK (action IN ('settle', 'release')),
    evidence_type text NOT NULL CHECK (evidence_type IN (
        'provider_usage', 'provider_invoice', 'operator_usage_review',
        'never_forwarded', 'provider_rejection', 'provider_confirmed_no_charge')),
    evidence text NOT NULL CHECK (length(evidence) BETWEEN 3 AND 2000),
    reason text NOT NULL CHECK (length(reason) BETWEEN 3 AND 500),
    actor_user_id bigint NOT NULL,
    idempotency_key text NOT NULL UNIQUE CHECK (length(idempotency_key) BETWEEN 1 AND 128),
    request_fingerprint text NOT NULL CHECK (length(request_fingerprint) = 64),
    usage_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_reconciliation_resolutions_lease
    ON accounting_reconciliation_resolutions(lease_token, created_at DESC);

