-- Provider credential refresh history is new product audit state. It records
-- outcome metadata only; token and client-secret material never enters SQL.
CREATE TABLE IF NOT EXISTS provider_credential_refresh_attempts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id uuid NOT NULL UNIQUE,
    account_id bigint NOT NULL CHECK (account_id > 0),
    source text NOT NULL CHECK (source IN ('dispatch', 'media')),
    version_before integer NOT NULL CHECK (version_before > 0),
    version_after integer,
    outcome text NOT NULL CHECK (outcome IN ('succeeded', 'failed')),
    error_code text,
    token_endpoint_host text NOT NULL CHECK (length(token_endpoint_host) BETWEEN 1 AND 253),
    started_at timestamptz NOT NULL,
    completed_at timestamptz NOT NULL,
    duration_ms integer NOT NULL CHECK (duration_ms >= 0 AND duration_ms <= 900000),
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK ((outcome = 'succeeded'
            AND version_after = version_before + 1
            AND error_code IS NULL)
        OR (outcome = 'failed'
            AND version_after IS NULL
            AND error_code IS NOT NULL
            AND length(error_code) BETWEEN 1 AND 120))
);

CREATE INDEX IF NOT EXISTS ix_provider_credential_refresh_attempts_account
    ON provider_credential_refresh_attempts(account_id, completed_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS ix_provider_credential_refresh_attempts_outcome
    ON provider_credential_refresh_attempts(outcome, completed_at DESC, id DESC);
