-- API key policy is native product state: scopes and expiry are explicit,
-- while this append-only log records who changed authorization boundaries.
ALTER TABLE user_api_keys
    ADD COLUMN IF NOT EXISTS scopes jsonb NOT NULL DEFAULT '["*"]'::jsonb,
    ADD COLUMN IF NOT EXISTS expires_at_ms bigint;

ALTER TABLE user_api_keys
    ADD CONSTRAINT ck_user_api_keys_scopes_array
    CHECK (jsonb_typeof(scopes) = 'array');

CREATE INDEX IF NOT EXISTS ix_user_api_keys_expiry
    ON user_api_keys(expires_at_ms)
    WHERE status = 'active' AND expires_at_ms IS NOT NULL;

CREATE TABLE IF NOT EXISTS api_key_audit_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_key_id bigint NOT NULL CHECK (api_key_id > 0),
    user_id bigint NOT NULL CHECK (user_id > 0),
    actor_user_id bigint NOT NULL CHECK (actor_user_id > 0),
    action text NOT NULL CHECK (action IN ('created', 'updated', 'rotated', 'revoked', 'expired', 'denied')),
    scopes jsonb NOT NULL DEFAULT '[]'::jsonb,
    expires_at_ms bigint,
    capability text,
    reason text,
    request_id text,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (jsonb_typeof(scopes) = 'array'),
    CHECK (capability IS NULL OR length(capability) BETWEEN 1 AND 80),
    CHECK (reason IS NULL OR length(reason) BETWEEN 1 AND 500),
    CHECK (request_id IS NULL OR length(request_id) BETWEEN 1 AND 200)
);

CREATE INDEX IF NOT EXISTS ix_api_key_audit_events_key
    ON api_key_audit_events(api_key_id, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS ix_api_key_audit_events_user
    ON api_key_audit_events(user_id, created_at DESC, id DESC);
