-- Durable content-policy mutation propagation and operational alert evidence.
-- Admin mutations and policy decisions remain PostgreSQL-authoritative; Garnet
-- carries only the disposable invalidation/revision signal.
CREATE TABLE IF NOT EXISTS content_policy_change_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision bigint NOT NULL,
    action text NOT NULL,
    rule_id bigint REFERENCES content_audit_rules(id) ON DELETE SET NULL,
    actor_id bigint,
    ip_address text,
    details jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    propagated_at timestamptz,
    claimed_by text,
    claimed_until timestamptz,
    attempts integer NOT NULL DEFAULT 0,
    last_error text,
    CONSTRAINT ck_content_policy_change_action
        CHECK (action IN ('created', 'updated', 'deleted')),
    CONSTRAINT ck_content_policy_change_revision CHECK (revision > 0)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_content_policy_change_revision
    ON content_policy_change_events(revision);
CREATE INDEX IF NOT EXISTS ix_content_policy_change_pending
    ON content_policy_change_events(propagated_at, claimed_until, id)
    WHERE propagated_at IS NULL;

CREATE TABLE IF NOT EXISTS content_policy_alert_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_key text NOT NULL UNIQUE,
    kind text NOT NULL,
    severity text NOT NULL,
    rule_id bigint REFERENCES content_audit_rules(id) ON DELETE SET NULL,
    user_id bigint,
    request_id text,
    stage text NOT NULL,
    code text NOT NULL,
    policy_revision bigint NOT NULL,
    details jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_content_policy_alert_kind
        CHECK (kind IN ('policy_block', 'classifier_unavailable', 'evaluator_unsupported')),
    CONSTRAINT ck_content_policy_alert_severity
        CHECK (severity IN ('warning', 'critical')),
    CONSTRAINT ck_content_policy_alert_stage
        CHECK (stage IN ('request', 'response')),
    CONSTRAINT ck_content_policy_alert_revision CHECK (policy_revision > 0)
);
CREATE INDEX IF NOT EXISTS ix_content_policy_alert_created
    ON content_policy_alert_events(created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS ix_content_policy_alert_kind_created
    ON content_policy_alert_events(kind, created_at DESC);
