-- Durable, encrypted notification delivery. Token material is never stored in plaintext.
CREATE TABLE IF NOT EXISTS email_delivery_outbox (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_key text NOT NULL UNIQUE,
    recipient text NOT NULL,
    kind text NOT NULL CHECK (kind IN ('password_reset', 'email_verification')),
    token_ciphertext text NOT NULL,
    expires_at timestamptz NOT NULL,
    status text NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'sending', 'sent', 'failed')),
    attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    available_at timestamptz NOT NULL DEFAULT now(),
    claimed_until timestamptz,
    last_error text,
    created_at timestamptz NOT NULL DEFAULT now(),
    sent_at timestamptz
);

CREATE INDEX IF NOT EXISTS ix_email_delivery_outbox_due
    ON email_delivery_outbox(status, available_at, claimed_until, id);
