-- Active provider refund commands have their own idempotency and recovery
-- boundary. A provider call may complete before the Platform process records
-- the result, so pending rows are deliberately retryable.
CREATE TABLE IF NOT EXISTS payment_refunds (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_order_id bigint NOT NULL REFERENCES payment_orders(id),
    user_id bigint NOT NULL,
    provider text NOT NULL,
    provider_order_id text,
    provider_payment_id text,
    provider_refund_id text,
    idempotency_key text NOT NULL,
    request_fingerprint text NOT NULL,
    amount numeric(20,2) NOT NULL CHECK (amount > 0),
    currency text NOT NULL,
    reason text NOT NULL DEFAULT '',
    status text NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'succeeded', 'failed', 'reconciliation_needed')),
    provider_status text,
    error_code text,
    error_detail text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz
);

ALTER TABLE payment_refunds
    DROP CONSTRAINT IF EXISTS ck_payment_refunds_provider_order_id;
ALTER TABLE payment_refunds
    ADD CONSTRAINT ck_payment_refunds_provider_order_id
    CHECK (provider_order_id IS NULL OR length(provider_order_id) BETWEEN 1 AND 128);

ALTER TABLE payment_refunds
    DROP CONSTRAINT IF EXISTS ck_payment_refunds_provider_payment_id;
ALTER TABLE payment_refunds
    ADD CONSTRAINT ck_payment_refunds_provider_payment_id
    CHECK (provider_payment_id IS NULL OR length(provider_payment_id) BETWEEN 1 AND 128);

ALTER TABLE payment_refunds
    DROP CONSTRAINT IF EXISTS ck_payment_refunds_currency;
ALTER TABLE payment_refunds
    ADD CONSTRAINT ck_payment_refunds_currency
    CHECK (length(currency) = 3 AND currency = upper(currency));

CREATE UNIQUE INDEX IF NOT EXISTS ux_payment_refunds_user_idempotency
    ON payment_refunds(user_id, idempotency_key);
CREATE UNIQUE INDEX IF NOT EXISTS ux_payment_refunds_provider_reference
    ON payment_refunds(provider, provider_refund_id)
    WHERE provider_refund_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_payment_refunds_order_active
    ON payment_refunds(payment_order_id)
    WHERE status IN ('pending', 'reconciliation_needed', 'succeeded');
CREATE INDEX IF NOT EXISTS ix_payment_refunds_order
    ON payment_refunds(payment_order_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_payment_refunds_recovery
    ON payment_refunds(status, updated_at)
    WHERE status IN ('pending', 'reconciliation_needed');
