import { createResource, createSignal, For, Show } from "solid-js";
import { get, post } from "../api/client";
type Order = { id: number; amount: number; currency: string; provider: string; status: string; createdAt: string };
type Subscription = { id: number; name: string; priceMonthly: number; quotaUsd: number; status: string; expiresAt?: string; renewalAt?: string; quotaGrantedUsd: number; quotaUsedUsd: number; quotaReservedUsd: number; quotaRemainingUsd: number };
type Plan = { id: number; name: string; priceMonthly: number; quotaUsd: number; interval: string; status: string };
type Referral = { code?: string; total_referrals: number; total_bonus: number };

export default function Billing() {
  const [orders, { refetch: refetchOrders }] = createResource(() => get<{ items: Order[] }>("/user/payments"));
  const [subscriptions, { refetch: refetchSubs }] = createResource(() => get<{ items: Subscription[] }>("/user/subscriptions"));
  const [plans] = createResource(() => get<{ items: Plan[] }>("/user/subscriptions/plans"));
  const [referral, { refetch: refetchReferral }] = createResource(() => get<Referral>("/user/referral/"));
  const [amount, setAmount] = createSignal("20"); const [planId, setPlanId] = createSignal("");
  const [redeemCode, setRedeemCode] = createSignal(""); const [message, setMessage] = createSignal(""); const [error, setError] = createSignal("");
  const notice = (text: string) => { setError(""); setMessage(text); };
  const fail = (err: unknown, fallback: string) => { setMessage(""); setError(err instanceof Error ? err.message : fallback); };
  const createOrder = async (event: Event) => { event.preventDefault(); try { await post("/user/payments/create", { amount: Number(amount()), currency: "USD", provider: "mock", description: "ScalaAPI credit" }, { "Idempotency-Key": crypto.randomUUID() }); refetchOrders(); notice("Payment order created."); } catch (err) { fail(err, "Unable to create order"); } };
  const subscribe = async (event: Event) => { event.preventDefault(); const selected = Number(planId()); if (!selected) return; try { await post("/user/subscriptions", { planId: selected, autoRenew: true }, { "Idempotency-Key": crypto.randomUUID() }); refetchSubs(); notice("Subscription activated."); } catch (err) { fail(err, "Unable to subscribe"); } };
  const changeSubscription = async (id: number, action: "cancel" | "renew") => { try { await post(`/user/subscriptions/${id}/${action}`, action === "renew" ? { autoRenew: true } : {}, { "Idempotency-Key": crypto.randomUUID() }); refetchSubs(); notice(action === "renew" ? "Subscription renewed." : "Subscription cancelled."); } catch (err) { fail(err, `Unable to ${action} subscription`); } };
  const redeem = async (event: Event) => { event.preventDefault(); try { const result = await post<{ bonus: number }>("/user/redeem/", { code: redeemCode().trim() }); setRedeemCode(""); notice(`Code redeemed. ${result.bonus.toFixed(2)} USD was added.`); } catch (err) { fail(err, "Unable to redeem code"); } };
  const generateReferral = async () => { try { await post("/user/referral/generate", {}); refetchReferral(); notice("Referral code ready to share."); } catch (err) { fail(err, "Unable to generate referral code"); } };
  return <div class="space-y-8"><div><p class="eyebrow">Account funding</p><h1 class="title">Billing</h1><p class="muted">Manage credit, subscriptions, redeem codes and referrals.</p></div>{message() && <p class="notice">{message()}</p>}{error() && <p class="error">{error()}</p>}
    <section class="panel"><div class="section-head"><h2>Add credit</h2></div><form class="flex max-w-md gap-3" onSubmit={createOrder}><input required class="field" type="number" min="1" max="1000000" step="0.01" value={amount()} onInput={e => setAmount(e.currentTarget.value)} /><button class="primary">Create order</button></form><div class="mt-6 overflow-x-auto"><table class="data-table"><thead><tr><th>Created</th><th>Amount</th><th>Provider</th><th>Status</th></tr></thead><tbody><For each={orders()?.items}>{order => <tr><td>{new Date(order.createdAt).toLocaleString()}</td><td>{order.amount.toFixed(2)} {order.currency}</td><td>{order.provider}</td><td>{order.status}</td></tr>}</For></tbody></table></div></section>
  <section class="panel"><div class="section-head"><h2>Subscriptions</h2></div><form class="flex max-w-xl flex-wrap gap-3" onSubmit={subscribe}><select required class="field max-w-sm" value={planId()} onChange={e => setPlanId(e.currentTarget.value)}><option value="">Choose a plan</option><For each={plans()?.items}>{plan => <option value={plan.id}>{plan.name} · ${plan.priceMonthly.toFixed(2)} / {plan.interval} · {plan.quotaUsd.toFixed(2)} USD quota</option>}</For></select><button disabled={!planId()} class="primary">Subscribe</button></form><Show when={subscriptions()?.items.length} fallback={<p class="muted mt-5">No subscriptions yet.</p>}><For each={subscriptions()?.items}>{sub => <div class="border-t border-slate-200 py-4 first:border-t-0"><div class="flex flex-wrap justify-between gap-2"><strong>{sub.name}</strong><span class="status">{sub.status}</span></div><p class="muted mt-1">${sub.priceMonthly.toFixed(2)} / month · {sub.quotaUsedUsd.toFixed(2)} / {sub.quotaGrantedUsd.toFixed(2)} USD used · {sub.quotaRemainingUsd.toFixed(2)} USD available</p><div class="mt-3 flex gap-3"><Show when={sub.status === "active"}><button class="secondary" onClick={() => changeSubscription(sub.id, "cancel")}>Cancel</button></Show><Show when={sub.status !== "active"}><button class="secondary" onClick={() => changeSubscription(sub.id, "renew")}>Renew</button></Show></div></div>}</For></Show></section>
    <div class="grid gap-8 lg:grid-cols-2"><section class="panel"><div class="section-head"><h2>Redeem a code</h2></div><form class="flex gap-3" onSubmit={redeem}><input required class="field" placeholder="Promotion code" value={redeemCode()} onInput={e => setRedeemCode(e.currentTarget.value)} /><button class="primary">Redeem</button></form><p class="muted mt-3">Each code can be used once per account.</p></section><section class="panel"><div class="section-head"><h2>Referral</h2><button class="secondary" onClick={generateReferral}>Generate code</button></div><Show when={referral()?.code} fallback={<p class="muted">Generate a personal referral code to get started.</p>}><code class="block break-all bg-slate-50 p-3 text-sm">{referral()?.code}</code><div class="mt-4 grid grid-cols-2 gap-4"><div><p class="metric-label">Referrals</p><p class="mt-1 text-xl font-semibold">{referral()?.total_referrals}</p></div><div><p class="metric-label">Bonus</p><p class="mt-1 text-xl font-semibold">{Number(referral()?.total_bonus ?? 0).toFixed(2)} USD</p></div></div></Show></section></div>
  </div>;
}
