import { createSignal, Show } from "solid-js";
import { A } from "@solidjs/router";
import { post } from "../api/client";

export default function Recovery() {
  const [email, setEmail] = createSignal(""); const [token, setToken] = createSignal(new URLSearchParams(window.location.search).get("token") ?? "");
  const [password, setPassword] = createSignal(""); const [message, setMessage] = createSignal("");
  const [error, setError] = createSignal("");
  const request = async (event: Event) => { event.preventDefault(); setError(""); setMessage(""); try { const result = await post<{ accepted: boolean; debug_token?: string }>("/auth/password-reset/request", { email: email() }); setMessage(result.debug_token ? `Development token: ${result.debug_token}` : "If the address exists, a reset message has been sent."); if (result.debug_token) setToken(result.debug_token); } catch (err) { setError(err instanceof Error ? err.message : "Unable to request recovery"); } };
  const confirm = async (event: Event) => { event.preventDefault(); setError(""); setMessage(""); try { await post("/auth/password-reset/confirm", { token: token(), newPassword: password() }); setMessage("Password changed. You can sign in now."); } catch (err) { setError(err instanceof Error ? err.message : "The reset token is invalid or expired"); } };
  return <div class="flex min-h-screen items-center justify-center bg-[#0b1220] px-5"><div class="w-full max-w-md bg-white p-8 shadow-2xl"><p class="mb-2 text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">ScalaAPI</p><h1 class="mb-1 text-2xl font-semibold">Recover access</h1><p class="mb-7 text-sm text-slate-500">Request a one-time reset token, then choose a new password.</p>{message() && <p class="notice mb-4">{message()}</p>}{error() && <p class="error mb-4">{error()}</p>}<form class="space-y-3" onSubmit={request}><h2 class="font-medium">Request reset</h2><input required type="email" class="field" placeholder="Email" value={email()} onInput={e => setEmail(e.currentTarget.value)} /><button class="primary w-full">Send reset request</button></form><div class="my-7 h-px bg-slate-200" /><form class="space-y-3" onSubmit={confirm}><h2 class="font-medium">Set new password</h2><input required class="field" placeholder="Reset token" value={token()} onInput={e => setToken(e.currentTarget.value)} /><input required minlength="12" type="password" class="field" placeholder="New password (12+ characters)" value={password()} onInput={e => setPassword(e.currentTarget.value)} /><button class="secondary w-full">Confirm password change</button></form><p class="mt-7 text-center text-sm text-slate-500"><A href="/login" class="font-medium text-slate-950 underline">Return to sign in</A></p></div></div>;
}
